<!-- BEGIN Logocode für Google Kundenrezensionen -->
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
<script>
    window.renderBadge = function() {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function() {
            window.gapi.ratingbadge.render(
                ratingBadgeContainer, {
                    // REQUIRED
                    "merchant_id": <?php echo $this->escapeHtml( $this->getStoreId() ) ?>,
                    // OPTIONAL
                    "position": "<?php echo $this->escapeHtml( $this->getBadgePosition() ) ?>"
                });
        });
    }
</script>
<!-- END Logocode für Google Kundenrezensionen -->