<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>
<script>
    window.renderOptIn = function() {
        window.gapi.load('surveyoptin', function() {
            window.gapi.surveyoptin.render(
                {
                    "merchant_id": <?php echo $this->escapeHtml( $this->getItemGoogleShoppingAccountId() ) ?>,
                    "order_id": "<?php echo $this->escapeHtml( $this->getOrderId() ) ?>",
                    "email": "<?php echo $this->escapeHtml( $this->order->getCustomerEmail() );?>",
                    "delivery_country": "<?php echo $this->escapeHtml( $this->getCustomerCountry() ) ?>",
                    "estimated_delivery_date": "<?php echo $this->getEstimatedDeliveryDate() ?>"
                });
        });
    }
</script>
